czekpass/czekpass-app

Gemfile.lock, db/migrate/20190813074335_add_user_id_to_businesses.rb, db/schema.rb, db/seeds.rb
seeds/added user_id to businesses table
=> seeds/added user_id to businesses table

app/models/purchase.rb, app/models/user.rb, db/schema.rb, db/seeds.rb
=> validates and seeds seemed to be aligned

app/controllers/products_controller.rb, app/views/businesses/show.html.erb, app/views/products/edit.html.erb, app/views/products/index.html.erb, app/views/products/new.html.erb
The product controller + associated views are working now.
=> Product business view controllers

app/controllers/users_controller.rb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
I finished the base for users controller + views.
=> users basic done

app/controllers/purchases_controller.rb, app/views/purchases/new.html.erb
Added some sudo code in the controller of what needs to be replaced once QR codes are integrated.
Also, added sudo code in new.html.erb of what needs to change once we figure how to identify a perk is valid to that business
=> purchases_controller

app/controllers/pages_controller.rb, app/models/business.rb, app/models/perk.rb, app/models/perk_template.rb, app/models/product.rb, app/models/user.rb, app/views/businesses/show.html.erb, app/views/pages/business_dashboard.html.erb, app/views/pages/business_page.html.erb, app/views/pages/discover.html.erb, app/views/products/show.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_perk_card.html.erb, config/routes.rb, db/migrate/20190814123454_add_perk_id_to_purchase.rb, db/migrate/20190814231343_change_providing_receiving_names_on_perks.rb, db/migrate/20190814232057_change_perk_template_receiving_product_id_to_product_id.rb, db/migrate/20190814232430_add_photo_to_users.rb, db/migrate/20190815022610_add_business_id_to_perks.rb, db/schema.rb, db/seeds.rb
Changes product and perks naming conventions:
**On perks**
- providing_business ==> patronized_business
- providing_purchase ==> purchased_product_id
- receiving_product ==> product_id 
This was done to resolve the business.perks association issue. That issue is not resolved yet, so a business_id field was added. This business_id is the id of the business that created the perk. 
The logic behind this change is that the main perspective is that of the business owner creating and offering perks. 
- The **business owner** chooses which **businesses were patronized** (patronized_business) by prospective customers.
- The **business owner** chooses which **products were purchased** (purchased_product) by prospective customers .
- The **business owner** associates a perk to **one of his or her …
=> Model work

app/models/product.rb, app/models/purchase.rb, app/models/saving.rb, app/models/user.rb
Does not have many perks through purchases, it has perks directly through the foreign key in the perks table.
A purchase has_many :perks, through: :product
A saving has one user through purchase, not belongs to user
=> Fixed associations with Savings & Purchases

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/controllers/purchases_controller.rb, app/controllers/users_controller.rb, app/views/pages/business_dashboard.html.erb, app/views/products/show.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb, app/views/users/validate.html.erb, config/routes.rb
=> Did the general validation flow

Gemfile.lock, app/assets/stylesheets/components/_navs_myles.scss, app/assets/stylesheets/pages/_home.scss, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/pages/discover.html.erb
The current location button now zooms to where you are on the map.
The profile logo on the footer is fixed
=> current-location zoom/profile logo fixed

app/assets/stylesheets/components/_filter-card.scss, app/assets/stylesheets/components/_global.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/discover.html.erb
Filter button now has a dropdown event listener on it.
Iterates through businesses within Canggu (will implement current location) and shows business category cards(will add links).
=> filter by category name

app/assets/stylesheets/components/_filter-card.scss, app/assets/stylesheets/components/_global.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/discover.html.erb
=> Signup form

app/controllers/pages_controller.rb, app/views/pages/discover.html.erb
Map search works by name, location(or closest location if it doesn't map exactly with location)
if it doesnt match either the map no longer deletes the markers
=> map searching works

app/assets/stylesheets/components/_card.scss, app/controllers/pages_controller.rb, app/models/product.rb, app/views/pages/business_dashboard.html.erb
Business dashboard now can show which "business partners" bring in the most reveue from their perks
=> revenue per business partner

app/views/shared/_product_card.html.erb
=> fixed flow to bus show page

app/controllers/users_controller.rb, app/views/businesses/edit.html.erb, app/views/businesses/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/business_dashboard.html.erb, app/views/shared/_nav.html.erb, app/views/shared/_product_card.html.erb
We fixed a lot of the user dashboard HTML issues, business photo display issues, redirection of user edit to dashboard, nav bar user photo, default images a bit in some areas, yeah.
=> Lots of photo + user dashboard issues fixed

app/javascript/packs/application.js, app/views/businesses/show.html.erb, app/views/pages/dashboard.html.erb, app/views/products/new.html.erb, app/views/shared/_nav.html.erb
Ability of business owner to add product tab added to sidebar.
=> Final days

app/models/perk.rb, app/models/product.rb, app/views/pages/Bus_dash_3.html.erb, db/seed_data.yml, db/seeds.rb
Perk claimed percentage
revenue from perks
removed discounted_price from seeds
=> bus_dash logic set, removed discounted_price from seeds

app/controllers/perks_controller.rb
Perk controller code should be working now for both scenarios.
=> Guido saved the day again

app/javascript/plugins/chart-bar-revenue.js
=> Fixed Bar CHart

app/controllers/products_controller.rb, app/views/perks/edit.html.erb, app/views/products/edit.html.erb, app/views/products/index.html.erb
=> Delete buttons and dashboard rerouting

app/javascript/plugins/chart-bar-revenue.js, app/javascript/plugins/init_mapbox.js
Some error handling for mapbox users with no perks. Error handling for charts if no data
=> Some error handling for maps
